name: Build VSCode Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install -g @vscode/vsce
        
      - name: Set Version Variable
        run: echo "version=$(0.0.1)" >> $GITHUB_ENV

      - name: Set Package Name Variable
        run: echo "package=pretty-purple-$version.vsix" >> $GITHUB_ENV

      - name: Build Extension
        run: vsce package --no-update-package-json $version

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.package }}
          path: ${{ env.package }}
