name: Build VSCode Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install @vscode/vsce
        
      - name: Set Version Variable
        run: echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Extension
        run: vsce package --no-update-package-json $version

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: vscode-extension
          path: pretty-purple-$version
