name: Build VSCode Extension

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Set Tag Name
        run: echo "TAG_NAME=pretty-purple-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Build Extension
        run: |
          vsce package --no-update-package-json
          VSIX_FILE=$(ls *.vsix)
          echo "PACKAGE_FILE=$VSIX_FILE" >> $GITHUB_ENV

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension
          path: ${{ env.PACKAGE_FILE }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: ${{ env.PACKAGE_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
