name: Build VSCode Extension

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install -g @vscode/vsce

      - name: Create a tag from current commit
        run: |
          TAG_NAME=pretty-purple-$(date +%Y%m%d-%H_%M_%S)
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
  

      - name: Set Package Name Variable
        run: echo "package=$TAG_NAME.vsix" >> $GITHUB_ENV

      - name: Build Extension
        run: vsce package --no-update-package-json $version

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.package }}
          path: ${{ env.package }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: ./*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
